title: "EP Templates"
description: "E-Portfolio Templates"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically ignored.
# _config.yml, .git, .svn, or .jekyll-cache.
exclude:
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Directory structure
collections_dir: .
collections:
  posts:
    output: true

# Markdown processing
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"